#!/bin/sh

(
echo "Set(\$DatabaseType, 'Pg');"
echo "Set(\$DatabaseUser, '$DB_ENV_POSTGRES_USER');"
echo "Set(\$DatabasePassword, '$DB_ENV_POSTGRES_PASSWORD');"
echo "Set(\$DatabaseName, '$DB_ENV_POSTGRES_DB');"
) > $RTCONFDIR/10-database-config.pl
